### ISSUE TITLE
Fetches empty db entry, database corrupted.

### ISSUE THREAD

**Issue by moretocome** [eglia/ff-oc-passwords#26]
Thank you for this great extension.

I am experiencing a small glitch though. With every database sync, I get this error notification:

> Some entries in your passwords database seem to be corrupted. Could not get all details for entry:
> 0: [user]

When I run `curl -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords` in terminal, I do get a list of all my passwords, but upon inspecting the list I find this entry:

> {"id":0,"user_id":"[user]","loginname":null,"website":"[user]","address":null,"pass":false,"properties":false,"notes":false,"creation_date":null,"deleted":false},

Notice that my user name shows up in the website field (I have replaced my real user name with [user]).
I have checked my db's  `oc_passwords` table, and there is no entry with `id=0`.

All of my actual user names/passwords are synced as well, so the error does not break functionality, it is just an annoyance to see the error notification on every sync.

EDIT:
I run Nextcloud 10.0.1 (stable) on Raspbian (Debian Linux 8.0) with nginx/1.10.1built with OpenSSL 1.0.2j.
Client is Firefox 49 on Linux Mint 17.3.

**Comment by maximusVII** [comment]
I guess it is related to the follwing issue [#80](https://github.com/fcturner/passwords/issues/280)

**Comment by ghost** [comment]
Indeed. But it is now tested and fixed in my latest master. (Passwords app)

**Comment by moretocome** [comment]
I upgraded to the latest Passwords app master through `git clone`, and the error disappeared, but now the ff extensions says `0 Logins in Database`.
In my Nextcloud log i see:
`Undefined index: id at /var/www/html/nextcloud/apps/passwords/service/passwordservice.php#50`
and
`Undefined offset: 73 at /var/www/html/nextcloud/apps/passwords/service/passwordservice.php#42`

**Comment by moretocome** [comment]
I upgraded to the latest Passwords app master through `git clone` even though I was already running version 20beta5, and the error disappeared, but now the ff extensions says ` 0 Logins in Database`.
In my Nextcloud log i see:
```Undefined index: id at /var/www/html/nextcloud/apps/passwords/service/passwordservice.php#50```
and
```Undefined offset: 73 at /var/www/html/nextcloud/apps/passwords/service/passwordservice.php#42```

**Comment by moretocome** [comment]
`curl -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords`
now gives me:

```
curl: (60) SSL certificate problem: self signed certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

My ISP is blocking port 80, so I am not able to use Lets Encrypt. Could you add an option to allow self signed certificates?

EDIT: I tried deleting and re-adding the certificate, making sure to store it permanently like suggested in #12 , but that did not work.

But I see these errors in the console:

```
ff-oc-passwords:Object { id: 33, user_id: "[user]", loginname: "", website: "[www]", address: "", pass: "49478a966f2a3e9dc26f3e9adb1c7704f74…", properties: "0b7cbf32a09cb635133c067c34b94f675ca…", notes: "", creation_date: "1970-01-01", deleted: false }api.js:34
ff-oc-passwords:0b7cbf32a09cb635133c067c34b94f675ca62055377aa25311410e6896298e97c69a4bc24f5434b8b52b3c246f24d723702e9d5510d03fe412cdbd732b43fbf251433a2149fa4bf2b1605667ea05aa3b1e053b6ae7de5b047155dcf04047ab9d97af3305d38c76c06388ffff22446015a114073157ffc2d157f68de35067a1fdbe752ec4fefb1254fb9ab1aa708a1629cebca9036dc923bbb73eb81dccd1af532d7a039c78088614068d171bff61ad20247c033b05f1ebde8a37adee1653fe265c6715d9f49e604d7518ba6d87b5ae200330a29f8270ecfd37473f82dc779e6cb5623248e5ce994732907a102e4594e536665797143fc8c29e8af971d52d53e44954f2df7df0286d8b06dadab55116025815770e490de9aa99277b7892d99931b9698b2a7ca6c9959cedf191095588157f53dc37301b950217f713536890ff6e07d7ee14fb8d91cff841f4698f3ee4d091756746e99caefdef9630680cb30b04788471d3b409e55549c6975c7249fe397c72a1ba14e0c88f4d6b6176e08485d2630f24d3209494fcb69a8b345e47d4dc3456547c9b287e2aapi.js:35
ff-oc-passwords:SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 818 of the JSON data
Stack trace:
jsonToObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://ff-oc-passwords/lib/api.js:31:20
fetchAllCallback/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://ff-oc-passwords/lib/api.js:160:30
api.js:36
ff-oc-passwords:Object { id: 72, user_id: "[user]", loginname: "", website: "[www]", address: "", pass: "fcf6de348f2d5723134e6a6cba2f17f90d7…", properties: "1620b54d57ba878839f31b5ddb2a3ea9fd3…", notes: "", creation_date: "1970-01-01", deleted: false }api.js:34
ff-oc-passwords:1620b54d57ba878839f31b5ddb2a3ea9fd305adacc9fc8c309160b56e9094a062e745950e7d6c71f366ddbcdf072f718f7032f2467abc09475234e3903d83d52934a899e7ceadbe8b774fdac061f23916dd526b0840fab433355c5038b13925cd2e71bfb963e5e8f8dd61485fab4f01984a691f23cf054738291fd6988d76c04eb6dfa71f42de37ed7ba4066704423a3f91106f611a8766098db63a4bd285dc3dfd13d9d40777f207d1acd2a21b8ac4f079ad6239292dd48b0cffe72153cfecec44497f70c54b301fc0e016b2afea79f367a024ede9c141d2b2293067c888780f118db7cb415fc56c8d3f9c0146ab9390d992bcbef02c4cac5d7061b62ceeda86f9f4a6b3766883e84f212ed97cf21f39d6d835aadd3831fc300b4ad92d9d3c99c25afda3877f85d56e58efab4ff1af6a4abf38944de53b490ecaf54a1765b64186a187481f7a204f5a1a49f8a01986c3a62cfddc048e761a2a967a2d74406109e41fa18377f9f12a973a50bbaae4f233cc07e3e7313e6eb24216bf427a2732d0fa9c37cee431fe3api.js:35
ff-oc-passwords:SyntaxError: JSON.parse: expected ':' after property name in object at line 1 column 786 of the JSON data
Stack trace:
jsonToObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://ff-oc-passwords/lib/api.js:31:20
fetchAllCallback/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://ff-oc-passwords/lib/api.js:160:30
api.js:36
ff-oc-passwords:TypeError: loginList[i] is null
Stack trace:
processLoginList@resource://gre/modules/commonjs/toolkit/loader.js -> resource://ff-oc-passwords/index.js:134:9
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:263:31
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:328:23
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:50:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:82:9
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/windows/observer.js:49:5
core.js:106
```

**Comment by maximusVII** [comment]
The issues is still persistent. I upgraded to the latest git master of the password app. After that point in time, the firefox add-on in saying that there are 0 entries in the database (which is not true)

Is it an issue of the password app or the firefox add-in?

![untitled](https://cloud.githubusercontent.com/assets/22932853/19958775/1edd6e00-a1a2-11e6-8dcb-7d44ab28db43.png)
.

**Comment by moretocome** [comment]
Great, new update seems to have fixed the issue :)
